---
- name: Create a availability set
  azure_rm_availabilityset:
    name: '{{pl_availabilityset_name}}'
    location: '{{pl_location}}'
    resource_group: '{{pl_resource_group_name}}'
    platform_update_domain_count: 5
    platform_fault_domain_count: 3
    sku: Aligned
    state: present
    auth_source: env
  environment:
    AZURE_SUBSCRIPTION_ID: '{{pl_azure_subscription_id}}'
    AZURE_CLIENT_ID: '{{pl_azure_client_id}}'
    AZURE_SECRET: '{{pl_azure_secret}}'
    AZURE_TENANT: '{{pl_azure_tenant}}'
